// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC1yAEfMaQfG2VsxkC_8pvq8Uzvc5D5ebQ',
    appId: '1:71229892932:web:06cdcadd9e025505d24f11',
    messagingSenderId: '71229892932',
    projectId: 'fresh-and-clean-mussafah',
    authDomain: 'fresh-and-clean-mussafah.firebaseapp.com',
    storageBucket: 'fresh-and-clean-mussafah.firebasestorage.app',
    measurementId: 'G-8Z5L2D9QX2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNMRiEKt6a3UfvnhlSZrHGrSKdHQRolq4',
    appId: '1:71229892932:android:906862b2f07f7181d24f11',
    messagingSenderId: '71229892932',
    projectId: 'fresh-and-clean-mussafah',
    storageBucket: 'fresh-and-clean-mussafah.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCbDeXRWsgAe8vx-b9Rcucs-Nk_EwxX0wQ',
    appId: '1:71229892932:ios:584e1cb08dca5abad24f11',
    messagingSenderId: '71229892932',
    projectId: 'fresh-and-clean-mussafah',
    storageBucket: 'fresh-and-clean-mussafah.firebasestorage.app',
    iosBundleId: 'com.cilyde.laundryOsExtended',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCbDeXRWsgAe8vx-b9Rcucs-Nk_EwxX0wQ',
    appId: '1:71229892932:ios:584e1cb08dca5abad24f11',
    messagingSenderId: '71229892932',
    projectId: 'fresh-and-clean-mussafah',
    storageBucket: 'fresh-and-clean-mussafah.firebasestorage.app',
    iosBundleId: 'com.cilyde.laundryOsExtended',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC1yAEfMaQfG2VsxkC_8pvq8Uzvc5D5ebQ',
    appId: '1:71229892932:web:4421c152bacdb78fd24f11',
    messagingSenderId: '71229892932',
    projectId: 'fresh-and-clean-mussafah',
    authDomain: 'fresh-and-clean-mussafah.firebaseapp.com',
    storageBucket: 'fresh-and-clean-mussafah.firebasestorage.app',
    measurementId: 'G-2JKGLSKFPP',
  );

}